# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77acd9048db67ee2d3f6d3d06c7c19ced07cd36452f8b31233bc2565d9858f906aec5e7d670f3cb4dff16a4cbb88cdef7d90912bd33af542585ea3748a9a1c4a

test:
  secret_key_base: 04240d81a620813bfa3515c97edfcce18b0e035c37261b14030eaf3d4ce3ca3f9af91e3d1f034e4b2e16a6f52045321303d7720c26e665952344530dcba1eb26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
